DROP TABLE IF EXISTS CREDIT_CARD;

CREATE TABLE CREDIT_CARD (
  card_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  card_number VARCHAR(16) NOT NULL,
  card_limit DOUBLE,
  balance DOUBLE
);